<?php
/* @var $container Zend\Navigation\Navigation */
$container = $this->container;
?>
<ul class="<?php echo $this->navigation()->menu()->getUlClass() ?>">
    <?php foreach ($container as $page): ?>

        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php $icon = $page->get('icon'); ?>
        <?php if (!$hasChildren): ?>
            <li<?php if ($page->isActive()) echo ' class="active"' ?>>
                <a 
                    href="<?php echo $page->getHref() ?>"
                    <?php if ($page->getTarget() != ""): ?>
                        target="<?php echo $page->getTarget(); ?>"
                    <?php endif; ?>
                    >
                    <?php if (!empty($icon)): ?>
                        <i class="<?php echo $page->get("icon"); ?>"></i>
                    <?php else: ?>
                        <i class="fa fa-folder"></i>
                    <?php endif; ?>
                    <span><?php echo $page->getLabel() ?></span>
                </a>
            </li>
        <?php else: ?>
            <li class="parent<?php if ($page->isActive(true)) echo ' active' ?>">
                <a href="<?php echo $page->getHref() ?>">
                    <?php if (!empty($icon)): ?>
                        <i class="<?php echo $page->get("icon"); ?>"></i>
                    <?php else: ?>
                        <i class="fa fa-folder"></i>
                    <?php endif; ?>
                    <span><?php echo $page->getLabel() ?></span>
                </a>
                <ul class="sub-menu">
                    <?php foreach ($page->getPages() as $child): ?>
                        <li<?php if ($child->isActive()) echo ' class="active"' ?>>
                            <a 
                                href="<?php echo $child->getHref() ?>"
                                <?php if ($child->getTarget() != ""): ?>
                                    target="<?php echo $child->getTarget(); ?>"
                                <?php endif; ?>
                                >
                                <?php echo $child->getLabel() ?>
                            </a>
                        </li>
                    <?php endforeach ?>
                </ul>
            </li>   
        <?php endif ?>
    <?php endforeach ?>
</ul>