<?php echo $this->doctype(); ?>
<html class="no-js">
<head>
    <?php echo $this->headTitle('JpgAdmin - Zend Framework 2 Admin Interface')->setSeparator(' - ')->setAutoEscape(false) ?>
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0">  -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    
    <?php echo $this->headLink()
                                // Admin Theme
                                ->prependStylesheet('http://rawgithub.com/JPG-Consulting/JpgAdmin/master/data/assets/css/offcanvas.css')
                                ->prependStylesheet('http://rawgithub.com/JPG-Consulting/JpgAdmin/master/data/assets/css/accordion.css')
                                //->prependStylesheet('/css/accordionmenu.css')
                                ->prependStylesheet('http://rawgithub.com/JPG-Consulting/JpgAdmin/master/data/assets/css/bootstrap-admin.css')
                                // Font Awesome
                                ->prependStylesheet('//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css')
                                // Latest compiled and minified CSS for Bootstrap
                                ->prependStylesheet('//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css')
    ?>
    
    <?php echo $this->headScript()->prependFile('//oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                  ->prependFile('//html5shiv.googlecode.com/svn/trunk/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',)) 
                                  ->prependFile('http://rawgithub.com/JPG-Consulting/JpgAdmin/master/data/assets/js/detect.js') ?>
</head>
<body>
    <!-- Admin menu -->
    <!-- <div id="adminmenu" class="offcanvas-menu">  -->
    <nav id="offcanvas-left">
        <?php echo $this->navigation('adminmenu')->menu()->setPartial('partial/jpgadmin_adminmenu.phtml')->render() ?>
    </nav>
    <!-- /Admin menu -->
    
    <div id="page-wrap">
        <!-- Fixed navbar -->
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <a href="#offcanvas-left" class="offcanvas-show offcanvas-left-toggle">
                  <i class="fa fa-bars"></i>
              </a>
              <a href="#" class="offcanvas-hide offcanvas-left-toggle">
                  <i class="fa fa-bars"></i>
              </a>
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="<?php echo $this->url('jpgadmin') ?>">Project name</a>
            </div>
            <div class="navbar-collapse collapse">
              <?php echo $this->navigation('adminbar')->menu()->setPartial('partial/jpgadmin_adminbar.phtml')->render() ?>
              <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <?php echo $this->zfcUserIdentity()->getDisplayname(); ?> <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <!-- 
                    <li><a href="<?php echo $this->url('zfcuser/changepassword') ?>"><i class="fa fa-user"></i>&nbsp;&nbsp;<?php echo $this->translate("My Profile") ?></a></li>
                    <li class="divider"></li>
                     -->
                    <li><a href="<?php echo $this->url('zfcuser/logout') ?>"><i class="fa fa-sign-out"></i>&nbsp;&nbsp;<?php echo $this->translate("Logout") ?></a></li>
                  </ul>
                </li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </div>
        
        
        <div id="content-wrap">
            <div id="content">
                <?php echo $this->content; ?>
            </div>
        </div>
    </div> <!-- /.page-wrapper -->
    
    <?php echo $this->inlineScript()
                                    ->prependFile('http://rawgithub.com/JPG-Consulting/JpgAdmin/master/data/assets/js/jquery.offcanvas.js')
                                    ->prependFile('http://rawgithub.com/JPG-Consulting/JpgAdmin/master/data/assets/js/jquery.accordion.js')
                                    // Latest compiled and minified JavaScript for Bootstrap
                                    ->prependFile('//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js')
                                    // jQuery (necessary for Bootstrap's JavaScript plugins and others) 
                                    ->prependFile('https://code.jquery.com/jquery.js') ?>
    <script type="text/javascript">
    $(document).ready(function() {
        $('.accordion').accordion();

        var selScrollable = '.scrollable';
     // Uses document because document will be topmost level in bubbling
     $(document).on('touchmove',function(e){
       e.preventDefault();
     });
     // Uses body because jQuery on events are called off of the element they are
     // added to, so bubbling would not work if we used document instead.
     $('body').on('touchstart', '#offcanvas-left', function(e) {
       if (e.currentTarget.scrollTop === 0) {
         e.currentTarget.scrollTop = 1;
       } else if (e.currentTarget.scrollHeight === e.currentTarget.scrollTop + e.currentTarget.offsetHeight) {
         e.currentTarget.scrollTop -= 1;
       }
     });             

     $('body').on('touchmove', '#offcanvas-left', function(e) {
    	    // Only block default if internal div contents are large enough to scroll
    	    // Warning: scrollHeight support is not universal. (http://stackoverflow.com/a/15033226/40352)
    	    if($(this)[0].scrollHeight > $(this).innerHeight()) {
    	        e.stopPropagation();
    	    }
     });

     var touchStartEvent;
     $('body').on('touchstart', '#content', function(e) {
         touchStartEvent = e;
     });
     
     $('body').on('touchmove', '#content', function(e) {
    	 if($(this)[0].scrollHeight > $(this).innerHeight()) {
        	 if ((e.originalEvent.pageY > touchStartEvent.originalEvent.pageY && this.scrollTop == 0) ||
        			 (e.originalEvent.pageY < touchStartEvent.originalEvent.pageY && $('body').scrollTop() + $('body')[0].offsetHeight >= $('body')[0].scrollHeight))
        	 {
        	     e.preventDefault();
        	 } else {
                 e.stopPropagation();
             }
    	 }
 	 });
        
    });
    </script>
</body>
</html>
