<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('JpgAdmin - Zend Framework 2 Admin Interface')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink()->prependStylesheet('/css/admin/style.css')
                                ->prependStylesheet('//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile('//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js')
                                  ->prependFile('//code.jquery.com/jquery.min.js')
                                  ->prependFile('//oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                  ->prependFile('//html5shiv.googlecode.com/svn/trunk/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',)) ?>

</head>
<body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('jpgadmin') ?>">JpgAdmin</a>
            </div>
            <div class="navbar-collapse collapse">
                <?php echo $this->navigation('admin_top_navigation')
                                ->menu()
                                ->setUlClass('nav navbar-nav')
                                ->setMaxDepth(0)
                                ->setRenderInvisible(false)?>
          
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <?php echo $this->zfcUserIdentity()->getDisplayname(); ?> <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- 
                            <li><a href="#">Account</a></li>
                            <li class="divider"></li>
                             -->
                            <li><a href="<?php echo $this->url('zfcuser/logout') ?>"><?php echo $this->translate("Sign out") ?></a></li>
                        </ul>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
    
    <div class="body-wrapper">

        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - 2012 by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
    
        </div> <!-- /container -->
        
    </div> <!-- /body-wrapper -->
    <?php echo $this->inlineScript() ?>
</body>
</html>