<?php echo $this->doctype(); ?>

<html lang="en" class="no-js">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('JpgAdmin - Zend Framework 2 Admin Interface')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink()->prependStylesheet('https://rawgithub.com/jamesflorentino/nanoScrollerJS/master/bin/css/nanoscroller.css')
                                ->prependStylesheet('//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css')
                                ->appendStylesheet('//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css')
				->appendStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,400italic,700,800')
				->appendStylesheet('http://rawgithub.com/JPG-Consulting/JpgAdmin/development/data/public/css/admin.menu.css')
                                ->appendStylesheet('http://rawgithub.com/JPG-Consulting/JpgAdmin/development/data/public/css/admin/style.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile('//oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                  ->prependFile('//html5shiv.googlecode.com/svn/trunk/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',)) 
                                  ->prependFile('http://rawgithub.com/JPG-Consulting/JpgAdmin/development/data/public/js/init.js') ?>

</head>
<body>
    
    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".admin-navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('jpgadmin') ?>">JpgAdmin</a>
            </div>
            <div class="navbar-collapse collapse">
                <?php echo $this->navigation('admin_top_navigation')
                                ->menu()
                                ->setUlClass('nav navbar-nav')
                                ->setMaxDepth(0)
				->setRenderInvisible(false)
                                ->setPartial('partial/admin_sidemenu.phtml'); ?>
          
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <?php echo $this->zfcUserIdentity()->getDisplayname(); ?> <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- 
                            <li><a href="#">Account</a></li>
                            <li class="divider"></li>
                             -->
                            <li><a href="<?php echo $this->url('zfcuser/logout') ?>"><?php echo $this->translate("Sign out") ?></a></li>
                        </ul>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
    
    <aside id="admin-menu" class="nano nscroller has-scrollbar">
        <div class="content">
            <?php echo $this->navigation('admin_navigation')
                            ->menu()
                            ->setUlClass('admin-nav')
                            ->setMaxDepth(0)
                            ->setRenderInvisible(false) ?>
        </div>
    </aside>
    
    <div id="page">
        <?php echo $this->content; ?>
        
        <footer>
            <p>&copy; 2013 - <?php echo date('Y') ?> by JPG-Consulting. All rights reserved.</p>
        </footer>
    </div>
    
    <?php echo $this->inlineScript()->prependFile('http://rawgithub.com/JPG-Consulting/JpgAdmin/development/data/public/js/jquery.collapsibleSidebar.js')
                                    ->prependFile('http://rawgithub.com/jamesflorentino/nanoScrollerJS/master/bin/javascripts/jquery.nanoscroller.min.js')
                                    ->prependFile('http://rawgithub.com/jamesflorentino/nanoScrollerJS/master/bin/javascripts/overthrow.min.js')
                                    ->prependFile('//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js')
                                    ->prependFile('//code.jquery.com/jquery.min.js') ?>
    <script type="text/javascript">
    $(function(){

        $('.nano').nanoScroller();
        $('#admin-menu .content').collapsibleSidebar();

    });
    </script>
</body>
</html>
